#!/usr/bin/env python

#Created by Bruno de Medeiros Feb 2019
#This script takes as input a *.loci file generated by ipyRAD
#and outputs the consensus of each locus in a fasta file

import StringIO, argparse
from Bio import AlignIO, SeqIO
from Bio.Align import AlignInfo
from Bio.Alphabet.IUPAC import IUPACAmbiguousDNA
from Bio.SeqRecord import SeqRecord

#this function parses population files to a dictionary
            
def parse_alleles_file(inpath):
    seqlist = []
    with open(inpath, 'r') as allfile:
        temp = ''
        for line in allfile:
            if '//' not in line and line.lstrip('\n'):
                temp = temp + line
            elif not line.rstrip('\n '): #sometimes there are blank lines...
                continue
            else:
                nchar = int(len(temp.split('\n')[0].split()[-1]))
                ntaxa = int(temp.count('\n'))
                temp = str(ntaxa) + '\t' + str(nchar) + '\n' + temp
                phylip = StringIO.StringIO(temp)
                alignment = AlignIO.read(phylip, "phylip-relaxed", alphabet=IUPACAmbiguousDNA())
                summary_align = AlignInfo.SummaryInfo(alignment)
                consensus = summary_align.dumb_consensus(threshold=0.5, ambiguous='N')
                seqlist.append(SeqRecord(consensus, 
                                         id=str(len(seqlist)), 
                                         description = '' ))
                phylip.close()
                temp = '' #zero temp again
    return seqlist

if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument('input', help = 'path to input file,*.loci generated by pyRAD')
    parser.add_argument('output', help = 'name of output file')
   
    args = parser.parse_args()
    
    #get alignments and add population names
    consensus_seqs = parse_alleles_file(args.input)
    
    #write output
    SeqIO.write(consensus_seqs, args.output, "fasta")
